const affirmations = [
  "I am worthy of good things.",
  "I give myself permission to do what is right for me.",
  "I trust that I am on the right path.",
  "I put my energy into things that matter to me.",
  "Asking for help is a sign of self-respect and self-awareness.",
  "I affirm and encourage others, as I do myself.",
  "I am allowed to ask for what I want and what I need.",
  "I am worthy of investing in myself.",
  "I have come farther than I would have ever thought possible, and I'm learning along the way.",
  "I have everything I need to succeed.",
  "I look forward to tomorrow and the opportunities that await me.",
  "I strive for joy, not for perfection.",
  "My body is beautiful in this moment and at its current size.",
  "My sensitivity is beautiful, and my feelings and emotions are valid.",
  "Today is an opportunity to grow and learn.",
  "I am grateful for the people I have in my life.",
  "I am kind and help inspire others to be kind.",
  "I’m doing my best and that is enough.",
  "I am allowed to take my own path.",
  "I put my energy into the things that matter to me.",
  "My future is bright.",
  "Taking small steps every day can help me achieve big goals.",
  "I am in a loving and supportive relationship.",
  "I am blessed with an incredible family and wonderful friends.",
  "I am becoming the best version of myself.",
  "I have the freedom and power to create the life I desire.",
  "I choose to be kind to myself and love myself unconditionally.",
  "Wherever I am on my journey is where I’m supposed to be.",
  "I deserve success.",
  "Success comes to me easily and effortlessly.",
  "I deserve to be healthy and feel good about myself.",
  "I can handle whatever comes my way.",
  "I can tackle any problem one step at a time.",
  "I attract positive things in my life.",
  "I radiate good energy into the world.",
  "I am capable of achieving great things.",
  "My goals and dreams are within reach.",
  "I am resilient.",
  "I know my worth.",
  "I am deserving of what I desire, and I will achieve it.",
  "I learn and grow through difficulty.",
];

export default affirmations;
